create or replace table `backcountry-data-team.{{ params.final_dataset_id }}.S5_LocAttr` as
select DISTINCT 
member_id,
member_name, 
DC_PO_TYPE_LOCATION,
catalog_id,
catalog_name,
order_source_id,
order_source_name,
order_source_group,
selling_channel_group,
location_group,
MERCH_LOCATION_GROUP,
DC_FLAG,
VDC_FLAG,
city,
state,
zipcode,
active_status,
STORE_OPEN_DATE,
STORE_CLOSE_DATE,
CLIMATE,
CORP_VOL_GROUP,
CAPACITY,
SQ_FOOTAGE,
LATITUDE,
LONGITUDE,
STORE_BANNER,
DROP_SHIP,
null as LOC_OPEN_1,
null as LOC_OPEN_2,
null as LOC_OPEN_3,
null as LOC_OPEN_4,
null as LOC_OPEN_5,
null as LOC_OPEN_6,
null as LOC_OPEN_7,
null as LOC_OPEN_8,
null as LOC_OPEN_9,
null as LOC_OPEN_10,
from
`backcountry-data-team.{{ params.final_dataset_id }}.s5_location` 
 
;